In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
import ast 

In [3]:
#importer dataset
data=pd.read_csv("Data_alphabet.csv")
x=data.iloc[:,1].values
x1=data.iloc[:,1]
X2=np.zeros((727,5))
for i in range (727):
    SS=np.array([0,0 ,0, 0 ,0])
    res = ast.literal_eval(x1[i])
    while( len(res) <5):
        res.append(180)
    arr=np.array(res,np.float16)*1/100
    X2[i]=arr

print ( X2) 
y=data.iloc[:,-1].values

[[0.65332031 1.12207031 0.04629517 0.42285156 1.79980469]
 [0.36181641 0.83203125 0.41064453 1.06542969 0.79394531]
 [0.58642578 0.79248047 0.14099121 1.09667969 0.76806641]
 ...
 [1.09863281 0.90429688 1.73046875 0.62744141 1.0390625 ]
 [0.96191406 0.86914062 1.35351562 1.16796875 1.04785156]
 [1.72753906 0.57080078 0.75927734 0.54296875 1.79980469]]


In [4]:
#apercu des données
print(y)

data.shape

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7
  7  7  7  7  7  7  7  7  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8
  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8

(727, 3)

In [17]:
x_train,x_test,y_train, y_test= train_test_split(X2,y,test_size=0.2)
print(x_test)


[[1.37792969 0.46679688 1.53613281 0.44873047 1.57128906]
 [1.54785156 0.83984375 1.1015625  0.40136719 1.50976562]
 [1.48535156 1.40136719 0.07550049 0.98583984 0.17675781]
 [0.63671875 1.33007812 1.54003906 0.49121094 1.40136719]
 [1.69726562 0.75048828 0.73388672 0.21374512 1.79980469]
 [0.72949219 1.42578125 0.41625977 0.96679688 1.11425781]
 [0.87792969 1.10351562 1.24023438 0.80957031 1.36914062]
 [1.07128906 0.95898438 1.3515625  0.88867188 1.13085938]
 [0.62646484 1.26855469 0.24938965 0.90185547 1.29101562]
 [0.86621094 0.98486328 0.32128906 1.42773438 1.79980469]
 [1.12207031 0.78173828 1.46777344 0.61816406 1.41113281]
 [0.53417969 1.35742188 0.80273438 0.99951172 1.70605469]
 [0.51025391 0.62011719 1.10449219 0.97998047 1.41503906]
 [1.07226562 0.91015625 1.48339844 0.42651367 1.5078125 ]
 [0.78613281 1.0078125  1.58886719 0.3269043  1.68847656]
 [0.83251953 0.98193359 0.39868164 1.53222656 1.11914062]
 [1.44335938 0.37988281 1.75585938 0.42651367 1.39257812]
 [1.33496094 0

In [6]:
# le modele svm
classifier= SVC(kernel='linear',random_state= 0)
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [7]:
#prediction sur le test set
y_pred=classifier.predict(x_test)
y_pred=np.array(y_pred,np.int8)
print(y_pred)
y_test=np.array(y_test,np.int8)
print (y_test)

[ 0 15  4 12  2  4  0  9 10  0  0  3 18 16  2 16 18  1 12  2  0  6  4  1
 18 16  0 12  6 18  1 12  6 11  5  9 12 19  1  9  0  5 12  9  2 12  4  1
 12  1  4  4 19 18  2  5 12  1  0  0  0  0  2  4 12 18 17 12  4  0  6 12
  4  4 13  5  2 11  1  5  4  1  4  0  9  4 18  9  2 12  1  4 13 10 11 10
  4 18 18  0  9  0  2 12  1 12 12 16 10  0 12 16 12 12  0  3  5  2  4 18
  5  1  0 18  1 16  1  5  0  2  5 12  9  4  6  2 16  5 18 11  9 12 18 18
  2  5]
[ 0 15 19 17 13  6 10  9  0  0  0  3  5 19 15 16 10  0 12  2  0 14  5  0
 18  3  0  9  5 16  0 14 14 11 11  3 14 19  1 19  0  5  8  9 13 12  6 14
 15  6 11  6 19 18 13  4 12 14  0  0  1  0  7 19 14 10  9  5  5  0  6 12
 11 10  7 11  2 11  1  5  4  6 14  0  8  4 18  7  2 12  5 19 13 15 11  0
 14  3 18 10  7 16 13 17 14  8 17 16  4  0  9  3 12 12  0  3  5  8  4 10
 11 15  0 16  1 15  6 11 10 13 11  8  7  5  6  2 16  5 11 11  7 15 18 16
  2 11]


In [8]:
confusion_matrix(y_pred,y_test)

array([[14,  1,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,
         1,  0,  0,  0],
       [ 3,  3,  0,  0,  0,  1,  3,  0,  0,  0,  0,  0,  0,  0,  3,  1,
         0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  5,  0,  1,
         0,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  3,  3,  0,  0,  0,  1,  2,  0,  0,  2,  0,
         0,  0,  0,  3],
       [ 0,  0,  0,  0,  1,  4,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  2,  0,  0,  0,  0,  0,  0,  0,  2,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  4,  1,  2,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  1],
       [ 2,  0,  0,  0,  1,  0

In [9]:
def nomclasse(ypredct):
    j=0
    A=data.iloc[:,0]
    if (ypredct==j):
        return A[j]
    if(ypredct==1):
        j=j+1
        return A[j*40]
    if(ypredct<15):
        while(j!= ypredct):
            j=j+1
        return A[j*39]
    else:
        while(j!= ypredct):
            j=j+1
        return A[j*37]

In [10]:
nomclasse(9)

'Gaaf'

In [18]:
import pickle
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(classifier, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(x_test,y_test)